
version = "1.0"

[gotosocial]

services = ["__APP__"]

name.en = "GoToSocial configuration panel"
name.fr = "Configuration de GoToSocial"

help.en = ""
help.fr = ""

#### ACCOUNTS CONFIG

[gotosocial.accounts]

name.en = "Account config"
name.fr = "Configuration des inscriptions"

help.en = "Config pertaining to creation and maintenance of accounts on the server, as well as defaults for new accounts."
help.fr = ""

[gotosocial.accounts.registration-open]
ask.en = "Open registrations?"
ask.fr = ""
bind = "accounts-registration-open:__FINALPATH__/config.yaml"
default = "false"
help.en = "Do we want people to be able to just submit sign up requests, or do we want invite only?"
help.fr = ""
type = "boolean"

[gotosocial.accounts.approval-required]
ask.en = "Approval required?"
ask.fr = ""
bind = "accounts-approval-required:__FINALPATH__/config.yaml"
default = "true"
help.en = "Do sign up requests require approval from an admin/moderator before an account can sign in/use the server?"
help.fr = ""
type = "boolean"

[gotosocial.accounts.reason-required]
ask.en = "Reason required?"
ask.fr = ""
bind = "accounts-reason-required:__FINALPATH__/config.yaml"
default = "true"
help.en = "Are sign up requests required to submit a reason for the request (eg., an explanation of why they want to join the instance)?"
help.fr = ""
type = "boolean"

#### MEDIA CONFIG

[gotosocial.media]
name.en = "Media config"
name.fr = "Configuration des médias"

help.en = "Config pertaining to user media uploads (videos, image, image descriptions)."
help.fr = ""

[gotosocial.media.image-max-size]
ask.en = "Maximum allowed image upload size in bytes."
ask.fr = ""
bind = "media-image-max-size:__FINALPATH__/config.yaml"
default = "2097152"
help.en = "Default: 2097152 -- aka 2MB"
help.fr = ""
type = "number"

[gotosocial.media.video-max-size]
ask.en = "Maximum allowed video upload size in bytes."
ask.fr = ""
bind = "media-video-max-size:__FINALPATH__/config.yaml"
default = "10485760"
help.en = "Default: 10485760 -- aka 10MB"
help.fr = ""
type = "number"

[gotosocial.media.description-min-chars]
ask.en = "Minimum amount of characters required as an image or video description."
ask.fr = ""
bind = "media-description-min-chars:__FINALPATH__/config.yaml"
default = "0"
help.en = "Default: 0 (not required)"
help.fr = ""
type = "number"

[gotosocial.media.description-max-chars]
ask.en = "Maximum amount of characters permitted in an image or video description."
ask.fr = ""
bind = "media-description-max-chars:__FINALPATH__/config.yaml"
default = "500"
help.en = "Default: 500."
help.fr = ""
type = "number"

[gotosocial.media.remote-cache-days]
ask.en = "Number of days to cache media from remote instances before they are removed from the cache."
ask.fr = ""
bind = "media-remote-cache-days:__FINALPATH__/config.yaml"
default = "30"
help.en = """\
Default: 30.\
A job will run every day at midnight to clean up any remote media older than the given amount of days. \
When remote media is removed from the cache, it is deleted from storage but the database entries for the media are kept so that it can be fetched again if requested by a user.\
If this is set to 0, then media from remote instances will be cached indefinitely.\
"""
help.fr = ""
type = "number"

### STATUSES CONFIG

[gotosocial.statuses]
name.en = "Status config"
name.fr = "Configuration des status"

help.en = "Config pertaining to the creation of statuses/posts, and permitted limits."
help.fr = ""

[gotosocial.statuses.max-chars]
ask.en = "Maximum amount of characters permitted for a new status."
ask.fr = ""
bind = "statuses-max-chars:__FINALPATH__/config.yaml"
default = "5000"
help.en = "Default: 5000. Note that going way higher than the default might break federation."
help.fr = ""
type = "number"

[gotosocial.statuses.cw-max-chars]
ask.en = "Maximum amount of characters allowed in the CW/subject header of a status."
ask.fr = ""
bind = "statuses-cw-max-chars:__FINALPATH__/config.yaml"
default = "100"
help.en = "Default: 100. Note that going way higher than the default might break federation."
help.fr = ""
type = "number"

[gotosocial.statuses.poll-max-options]
ask.en = "Maximum amount of options to permit when creating a new poll."
ask.fr = ""
bind = "statuses-poll-max-options:__FINALPATH__/config.yaml"
default = "6"
help.en = "Default: 6. Note that going way higher than the default might break federation."
help.fr = ""
type = "number"

[gotosocial.statuses.poll-option-max-chars]
ask.en = "Maximum amount of characters to permit per poll option when creating a new poll."
ask.fr = ""
bind = "statuses-poll-option-max-chars:__FINALPATH__/config.yaml"
default = "50"
help.en = "Default: 50. Note that going way higher than the default might break federation."
help.fr = ""
type = "number"

[gotosocial.statuses.media-max-files]
ask.en = "Maximum amount of media files that can be attached to a new status."
ask.fr = ""
bind = "statuses-media-max-files:__FINALPATH__/config.yaml"
default = "6"
help.en = "Default: 6. Note that going way higher than the default might break federation."
help.fr = ""
type = "number"

### NGINX CONFIG

[nginx]

services = ["nginx"]

name.en = "nginx configuration"
name.fr = "Configuration de nginx"

[nginx.config]
name.en = "nginx configuration"
name.fr = "Configuration de nginx"

help.en = "Config pertaining to the Web server."
help.fr = ""

[nginx.config.max-client_max_body_size]
ask.en = "Sets the maximum allowed size of uploaded files."
ask.fr = ""
bind = "client_max_body_size:/etc/nginx/conf.d/__DOMAIN__/__APP__.conf"
default = "50M"
help.en = "Default: 50M."
help.fr = ""
type = "string"

## ---------------------------------------------------------------------
## IMPORTANT: with the exception of bind=null questions,
## question IDs should almost **always** correspond to an app setting
## initialized / reused during install/upgrade.
## Not doing so may result in inconsistencies between the config panel mechanism
## and the use of ynh_add_config
## ---------------------------------------------------------------------
