version = "1.0"

[main]

services = ["__APP__"]

name.en = "Main configuration"
name.fr = "Configuration principale"

help = "Here you can easily configure some things about your GoToSocial instance."


	[main.accounts]

	name = "Accounts config"

	help = "Config pertaining to creation and maintenance of accounts on the server, as well as defaults for new accounts."

	[main.accounts.accounts_registration_open]
	ask.en = "Open registrations?"
	ask.fr = "Inscriptions ouvertes ?"
	bind = "accounts-registration-open:__INSTALL_DIR__/config.yaml"
	choices = ["true", "false"]
	default = "false"
	help.en = "Do we want people to be able to just submit sign up requests, or do we want invite only?"
	help.fr = "Voulez-vous que les gens puissent simplement envoyer des demandes d'inscription, ou voulez-vous qu'iels doivent être invité-e-s ?"
	type = "select"

	[main.accounts.accounts_approval_required]
	ask.en = "Approval required?"
	ask.fr = "Validation requise ?"
	bind = "accounts-approval-required:__INSTALL_DIR__/config.yaml"
	choices = ["true", "false"]
	default = "true"
	help.en = "Do sign up requests require approval from an admin/moderator before an account can sign in/use the server?"
	help.fr = "Les demandes d'inscription doivent-elles être approuvées par un-e administrateur-ice/modérateur-ice avant qu'un compte puisse se connecter/utiliser le serveur ?"
	type = "select"

	[main.accounts.accounts_reason_required]
	ask.en = "Reason required?"
	ask.fr = "Motif requis ?"
	bind = "accounts-reason-required:__INSTALL_DIR__/config.yaml"
	choices = ["true", "false"]
	default = "true"
	help.en = "Are sign up requests required to submit a reason for the request (eg., an explanation of why they want to join the instance)?"
	help.fr = "Les demandes d'inscription doivent-elles être motivées (par exemple, par une explication de la raison pour laquelle la personne souhaite rejoindre l'instance) ?"
	type = "select"
