#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "gotosocial"
name = "GoToSocial"
description.en = "Fast ActivityPub social network server written in Go"
description.gl = "Un servidor áxil para a rede social ActivityPub escrito en Go"
description.ca = "Un servidor de xarxa social basat en ActivityPub escrit en GO"
description.fr = "Serveur de réseau social véloce basé sur ActivityPub écrit en Go"

version = "0.15.0~ynh2"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "AGPL-3.0-only"
website = "https://gotosocial.org/"
admindoc = "https://docs.gotosocial.org/en/latest/"
userdoc = "https://docs.gotosocial.org/en/latest/"
code = "https://github.com/superseriousbusiness/gotosocial"

[integration]
yunohost = ">= 11.2.6"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "100M"
ram.runtime = "100M"

[install]
[install.domain]
type = "domain"

[install.admin]
ask.en = "Name your admin user for GoToSocial"
ask.gl = "Nome da usuaria administradora en GoToSocial"
ask.ca = "Nom pel compte d'administració de GoToSocial"
ask.fr = "Nommez votre compte administrateur pour GoToSocial"
help.en = "Must be in lower case and without special characters."
help.gl = "Ten que ser con minúsculas e sen caracteres especiais."
help.ca = "Ha de ser en minúscules i sense caràcters especials."
help.fr = "Doit être en minuscule et sans caractère special."
type = "string"
example = "johndoe"

[install.email]
ask.en = "The email adress of your admin account."
ask.gl = "O enderezo de correo electrónico da conta Admin."
ask.ca = "Adreça de correu pel compte d'administració."
ask.fr = "L'adresse e-mail de votre compte admin."
type = "string"
example = "johndoe@example.com"

[install.password]
help.en = "Must contain: upper case, lower case, number and special character."
help.gl = "Ten que conter: maiúscula, minúscula, número e caracteres especiais."
help.ca = "Ha de tenir: majúscules, minúscules, xifres i caràcters especials."
help.fr = "Il doit contenir : majuscule, minuscule, chiffre et caractère spécial."
type = "password"

[install.accounts_registration_open]
ask.en = "Open registration?"
ask.ar = "التسجيلات مفتوحة؟"
ask.gl = "Rexistro aberto?"
ask.ca = "Registres oberts?"
ask.fr = "Inscriptions ouvertes ?"
help.en = "Allow people to submit new sign-up / registration requests via the form at `/signup`."
help.gl = "Queres permitir que calquera poida solicitar unha conta (verdadeiro), ou queres que só sexa a través de convite (falso)?"
help.ca = "Voleu que la gent puguin enviar peticions de registre (true), o voleu que les registres es facin únicament per invitació (false)?"
help.fr = "Permettre aux personnes de déposer de nouvelles demandes d'inscription via le formulaire à l'adresse `/signup`."
type = "boolean"
default = false

[install.accounts_reason_required]
ask.en = "Request registration reason?"
ask.gl = "Requerir razón para crear conta?"
ask.ca = "Motiu de la petició de registre?"
ask.fr = "Demande de motif pour les inscriptions ?"
help.en = "Are sign up requests required to submit a reason for the request (eg., an explanation of why they want to join the instance)?"
help.gl = "Requerir que a solicitante indique un motivo á hora de solicitar a creación da conta. (ex., explicación de por que quere unirse á instancia)"
help.ca = "S'ha d'afegir un motiu a la petició de registre (per exemple, el motiu pel qual volen unir-se a la instància)?"
help.fr = "Les demandes d'inscription doivent-elles être accompagnée d'un motif (par exemple, une explication de la raison pour laquelle la personne veut rejoindre l'instance) ?"
type = "boolean"
default = true

[resources]
[resources.sources.main]
in_subdir = false
i386.url = "https://github.com/superseriousbusiness/gotosocial/releases/download/v0.16.0-rc3/gotosocial_0.16.0-rc3_linux_386.tar.gz"
i386.sha256 = "7755365763749148e6278ec728aa9cb0827537735ca142165ffda901118354b2"
amd64.url = "https://github.com/superseriousbusiness/gotosocial/releases/download/v0.16.0-rc3/gotosocial_0.16.0-rc3_linux_amd64.tar.gz"
amd64.sha256 = "49ebdf55af3aaaf8eb48a5d877a75acdf9f46154cdf960e39805c564a9f91b1c"
armv6.url = "https://github.com/superseriousbusiness/gotosocial/releases/download/v0.16.0-rc3/gotosocial_0.16.0-rc3_linux_armv6.tar.gz"
armv6.sha256 = "c14b669906000611a9b898881bb55ec4d301ebbd96a3a051607828706fa3f1cd"
armv7.url = "https://github.com/superseriousbusiness/gotosocial/releases/download/v0.16.0-rc3/gotosocial_0.16.0-rc3_linux_armv7.tar.gz"
armv7.sha256 = "24d631f2dc46dc73617d0c8db0cb4754d6cb8068112fa35ced2804e57069b1c0"
arm64.url = "https://github.com/superseriousbusiness/gotosocial/releases/download/v0.16.0-rc3/gotosocial_0.16.0-rc3_linux_arm64.tar.gz"
arm64.sha256 = "3a56ddb9babb6726e0980dec21b85859442b8247822e4388d3249c833aa3a830"

autoupdate.asset.i386 = "gotosocial_.*linux_386.tar.gz$"
autoupdate.asset.amd64 = "gotosocial_.*linux_amd64.tar.gz$"
autoupdate.asset.armv6 = "gotosocial_.*linux_armv6.tar.gz$"
autoupdate.asset.armv7 = "gotosocial_.*linux_armv7.tar.gz$"
autoupdate.asset.arm64 = "gotosocial_.*linux_arm64.tar.gz$"
autoupdate.strategy = "latest_github_release"

[resources.system_user]
allow_email = true

[resources.install_dir]

[resources.data_dir]

[resources.permissions]
main.url = "/"
main.allowed = "visitors"
main.protected = true
main.show_tile = false

[resources.ports]

[resources.apt]
packages = "postgresql, postgresql-contrib"

[resources.database]
type = "postgresql"
