packaging_format = 2

id = "gotosocial"
name = "GoToSocial"
description.en = "ActivityPub social network server"
description.fr = "Serveur de réseau social basé sur ActivityPub"

version = "0.11.1~ynh4"

maintainers = ["OniriCorpe"]

[upstream]
license = "AGPL-3.0-only"
website = "https://gotosocial.org/"
demo = ""
admindoc = "https://docs.gotosocial.org/en/latest/"
userdoc = "https://docs.gotosocial.org/en/latest/"
code = "https://github.com/superseriousbusiness/gotosocial"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Must contain: upper case, lower case, number and special character."
    help.fr = "Il doit contenir : majuscule, minuscule, chiffre et caractère spécial."
    type = "password"

    [install.accounts_registration_open]
    ask.en = "Open registration?"
    ask.fr = "Inscriptions ouvertes ?"
    help.en = "Do you want people to be able to just submit sign up requests (true), or do you want invite only (false)?"
    help.fr = "Voulez-vous que les gens puissent envoyer des demandes d'inscription (true) ou voulez-vous que les inscriptions soient uniquement sur invitation (false) ?"
    type = "boolean"
    default = false

    [install.accounts_approval_required]
    ask.en = "Registration approval?"
    ask.fr = "Vérification manuelle des inscriptions ?"
    help.en = "Do sign up requests require approval from an admin/moderator before an account can sign in/use the server?"
    help.fr = "Les demandes d'inscription doivent-elles être approuvées par un-e administrateur-ice/modérateur-ice avant qu'un compte puisse se connecter et utiliser le serveur ?"
    type = "boolean"
    default = true

    [install.accounts_reason_required]
    ask.en = "Request registration reason?"
    ask.fr = "Demande de motif pour les inscriptions ?"
    help.en = "Are sign up requests required to submit a reason for the request (eg., an explanation of why they want to join the instance)?"
    help.fr = "Les demandes d'inscription doivent-elles être accompagnée d'un motif (par exemple, une explication de la raison pour laquelle la personne veut rejoindre l'instance) ?"
    type = "boolean"
    default = true

[resources]
        [resources.sources.main]
        in_subdir = false
        arm64.url = "https://github.com/superseriousbusiness/gotosocial/releases/download/v0.11.1/gotosocial_0.11.1_linux_arm64.tar.gz"
        arm64.sha256 = "d5478c5833df4c7a0510b452546640e10575d2fa45fa43dbbc2e2714f762362a"
        armhf.url = "https://github.com/superseriousbusiness/gotosocial/releases/download/v0.11.1/gotosocial_0.11.1_linux_armv7.tar.gz"
        armhf.sha256 = "6c19c23f7476ab0cd5e7e698bfd47bafa582eba84b810dcb8539e97a419cc136"
        i386.url = "https://github.com/superseriousbusiness/gotosocial/releases/download/v0.11.1/gotosocial_0.11.1_linux_386.tar.gz"
        i386.sha256 = "f66f455c7406ac40ff04320cb8f030b5affe8acd39937a8727b0ea53887c7227"
        amd64.url = "https://github.com/superseriousbusiness/gotosocial/releases/download/v0.11.1/gotosocial_0.11.1_linux_amd64.tar.gz"
        amd64.sha256 = "4e44a5cb4044a523c51b5d178dfd06efb077a17dac22a9a170d6204cb7aed407"

    [resources.system_user]
    allow_email = true

    [resources.ports]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql, postgresql-contrib"

    [resources.database]
    type = "postgresql"
