packaging_format = 2

id = "gotosocial"
name = "GoToSocial"
description.en = "ActivityPub social network server"
description.fr = "Serveur de réseau social basé sur ActivityPub"

version = "0.9.0~ynh1"

maintainers = ["OniriCorpe"]

[upstream]
license = "AGPL-3.0-only"
website = "https://gotosocial.org/"
demo = ""
admindoc = "https://docs.gotosocial.org/en/latest/"
userdoc = "https://docs.gotosocial.org/en/latest/"
code = "https://github.com/superseriousbusiness/gotosocial"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"
    full_domain = true

    [install.admin]
    type = "user"

    [install.email]
    ask.en = "The email adress of your admin account."
    ask.fr = "L'adresse e-mail de votre compte admin."
    type = "string"
    example = "johndoe@example.com"

    [install.password]
    help.en = "Must contain: upper case, lower case, number and special character."
    help.fr = "Il doit contenir : majuscule, minuscule, chiffre et caractère spécial."
    type = "password"

    [install.accounts_registration_open]
    ask.en = "Open registration?"
    ask.fr = "Inscriptions ouvertes ?"
    help.en = "Do you want people to be able to just submit sign up requests (true), or do you want invite only (false)?"
    help.fr = "Voulez-vous que les gens puissent envoyer des demandes d'inscription (true) ou voulez-vous que les inscriptions soient uniquement sur invitation (false) ?"
    type = "boolean"
    default = false

    [install.accounts_approval_required]
    ask.en = "Registration approval?"
    ask.fr = "Vérification manuelle des inscriptions ?"
    help.en = "Do sign up requests require approval from an admin/moderator before an account can sign in/use the server?"
    help.fr = "Les demandes d'inscription doivent-elles être approuvées par un-e administrateur-ice/modérateur-ice avant qu'un compte puisse se connecter et utiliser le serveur ?"
    type = "boolean"
    default = true

    [install.accounts_reason_required]
    ask.en = "Request registration reason?"
    ask.fr = "Demande de motif pour les inscriptions ?"
    help.en = "Are sign up requests required to submit a reason for the request (eg., an explanation of why they want to join the instance)?"
    help.fr = "Les demandes d'inscription doivent-elles être accompagnée d'un motif (par exemple, une explication de la raison pour laquelle la personne veut rejoindre l'instance) ?"
    type = "boolean"
    default = true

[resources]
        [resources.sources.main]
        in_subdir = false
        arm64.url = "https://github.com/superseriousbusiness/gotosocial/releases/download/v0.9.0/gotosocial_0.9.0_linux_arm64.tar.gz"
        arm64.sha256 = "6b3f543ef9e86953b74b859556996ee533a73fa2ec7ea035b9f392589e3c188b"
        armel.url = "https://github.com/superseriousbusiness/gotosocial/releases/download/v0.9.0/gotosocial_0.9.0_linux_armv6.tar.gz"
        armel.sha256 = "6a7508c40309a621246f351e95c2bef763b37fda5a8e1f3fe2485d7805973eb1"
        armhf.url = "https://github.com/superseriousbusiness/gotosocial/releases/download/v0.9.0/gotosocial_0.9.0_linux_armv7.tar.gz"
        armhf.sha256 = "41f932878ed3da809aa80dbfab51f0d84c6edc8283ee1893b46ee0338eb7ac01"
        i386.url = "https://github.com/superseriousbusiness/gotosocial/releases/download/v0.9.0/gotosocial_0.9.0_linux_386.tar.gz"
        i386.sha256 = "73cf171ae72a06dd3da669ffedd03da545a143c4965dd9585ad3586a25c734c2"
        amd64.url = "https://github.com/superseriousbusiness/gotosocial/releases/download/v0.9.0/gotosocial_0.9.0_linux_amd64.tar.gz"
        amd64.sha256 = "9b802061eb694508f1876486738b3a4062474eb4df9d864c5e293283c1756337"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql postgresql-contrib"

    [resources.database]
    type = "postgresql"
