test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.9a6d018337c7d83193282830ff9d9e9b0ae3a733.name = "Upgrade from 0.6.0~ynh1"
