test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.admin = "xana"
    args.email = "user@example.com"

