test_format = 1.0

<<<<<<< Updated upstream
[default]
=======
[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.admin="xana"
>>>>>>> Stashed changes
