test_format = 1.0

[default]

# GTS don't support it
exclude = [ "change_url" ]

# -------------------------------
# Default args to use for install
# -------------------------------

args.admin = "xana"
args.email = "ci-test@example.com"
args.password = "vYh8io7r*@P&zyo!6ZhBqQQ%8M5D4M"
# false by default
args.accounts_registration_open = 1
# true by default
args.accounts_reason_required = 0

# -------------------------------
# Commits to test upgrade from
# -------------------------------

test_upgrade_from.cb64af86.name = "Upgrade from 0.16.0~ynh2 (latest alpha)"

# -------------------------------
# additional tests suite
# -------------------------------
